<a href="https://colab.research.google.com/github/Shivaram17/AccEngine_PythonDemoCodes/blob/main/10014Incremental_SummaryReport.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd
from datetime import datetime
res = pd.to_datetime('today').strftime('%d-%b-%Y')
def summary(non, mismatch):
  data = {'Date': res,
          'Total_Non-std': [non],
          'Total_Mismatch': [mismatch],
          'Non-std_fixed': [0],
          'Mismatch_fixed':[0],
          }
  df = pd.DataFrame(data)
  df['Total_Non-std'] = df['Total_Non-std'].astype(int)
  print(df)
  return df

non = 5000
mismatch = 14000
df1 =summary(non, mismatch)
# df1.to_excel('summary.xlsx')
df2 = pd.read_excel('summary.xlsx', keep_default_na = False)
df2  = df2.append(df1)
l = len(df2) 
print(l)
n = (int(df2.iloc[l-2, 2]) - int(df2.iloc[l-1, 2]))
m = int(df2.iloc[l-2, 3]) - int(df2.iloc[l-1, 3])
df2.iloc[l-1, 4] = n
df2.iloc[l-1, 5] = m
df2

          Date  Total_Non-std  Total_Mismatch  Non-std_fixed  Mismatch_fixed
0  12-Apr-2022           5000           14000              0               0
2

,Unnamed: 0,Date,Total_Non-std,Total_Mismatch,Non-std_fixed,Mismatch_fixed
0,0.0,12-Apr-2022,6000,17000,0,0
0,NaN,12-Apr-2022,5000,14000,1000,3000